version: '3.8'
volumes:
  postgres-data:
    driver: local

services:

#  golang:
#    build: .
#    ports:
#      - 8081:8081
#    restart: on-failure
#    depends_on:
#     - keycloak

  keycloak:
    image: donaldov/keycloack:7.0.1
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak